apiVersion: v1
kind: Service
metadata:
  name: netology-fops-23-diplom-service
  namespace: netology-fops-23-diplom-namespace
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
