name: netology test site

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
#  pull_request:
#    branches: [ "master" ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: netology
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (branch)
        if: ${{ github.ref_type != 'tag' }}
        uses: docker/build-push-action@v6
        with:
          context: .                    
          file: ./Dockerfile            
          push: true                    
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/netology-diplom-repository:latest
      
      - name: Build and push (tag)
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@v6
        with:
          context: .                    
          file: ./Dockerfile            
          push: true                    
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/netology-diplom-repository:${{ github.ref_name }}

      - name: Configure Kubernetes (only for tag)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      - name: Deploy to Kubernetes (tag)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          kubectl apply -f k8s/ -n netology-fops-23-diplom-namespace
          kubectl set image deployment/diplom-webapp diplom-test-site=${{ secrets.DOCKER_USERNAME }}/netology-diplom-repository:${{ github.ref_name }} -n netology-fops-23-diplom-namespace
